language: python
python:
- "3.4"
install:
- python setup.py install
- pip install python-coveralls --use-mirrors
script: cd counterparty; py.test --cov-config .coveragerc --cov-report term-missing --cov ./ --skiptestbook=all
notifications:
  slack:
    secure: cl0G5fWZNnIK5VQ6BPZ4RtwVO2/nfvX/zjhljfF6cQ20OKyvyiJHq+e67fl2pkCKDlqlEqSWaQJ6G52YzUpDQmf+o7qpH6YnkFxSqYp5h4YF1hJw4sCHJ7bVSLrjogWxU8QaNvH7YpL4YkGe+WOau2FgoIZOcMt6hhKrvWclfuc=
after_success:
- coveralls
