[package]
name = "counterparty-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
config = "0.13"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
hex = "0.4.3"
bitcoin = "0.32.5"
bip39 = "2.0.0"
cocoon = "0.4.0"
rand = "0.8"
thiserror = "1.0"
lazy_static = "1.4.0"